# Generated by Django 5.2.4 on 2025-07-10 07:47

from django.db import migrations
from datetime import date

def create_mock_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Customer = apps.get_model('users', 'Customer')
    Company = apps.get_model('users', 'Company')
    Service = apps.get_model('services', 'Service')
    ServiceRequest = apps.get_model('services', 'ServiceRequest')

    # Clear existing data to prevent duplicates on re-run
    User.objects.all().delete()

    # Create Customer Users
    user1 = User.objects.create_user(username='customer1', email='customer1@example.com', password='password123', is_customer=True)
    customer1 = Customer.objects.create(user=user1, date_of_birth=date(1990, 5, 15))

    user2 = User.objects.create_user(username='customer2', email='customer2@example.com', password='password123', is_customer=True)
    customer2 = Customer.objects.create(user=user2, date_of_birth=date(1985, 10, 20))

    # Create Company Users
    user_plumber = User.objects.create_user(username='plumberco', email='plumber@example.com', password='password123', is_company=True)
    company_plumber = Company.objects.create(user=user_plumber, field='Plumbing')

    user_electrician = User.objects.create_user(username='sparkyco', email='sparky@example.com', password='password123', is_company=True)
    company_electrician = Company.objects.create(user=user_electrician, field='Electricity')

    user_carpenter = User.objects.create_user(username='woodworks', email='woodworks@example.com', password='password123', is_company=True)
    company_carpenter = Company.objects.create(user=user_carpenter, field='Carpentry')

    user_gardener = User.objects.create_user(username='greenfingers', email='greenfingers@example.com', password='password123', is_company=True)
    company_gardener = Company.objects.create(user=user_gardener, field='Gardening')

    user_painter = User.objects.create_user(username='colorco', email='colorco@example.com', password='password123', is_company=True)
    company_painter = Company.objects.create(user=user_painter, field='Painting')

    user_ac = User.objects.create_user(username='coolair', email='coolair@example.com', password='password123', is_company=True)
    company_ac = Company.objects.create(user=user_ac, field='Air Conditioner')

    user_homemachines = User.objects.create_user(username='fixitall', email='fixitall@example.com', password='password123', is_company=True)
    company_homemachines = Company.objects.create(user=user_homemachines, field='Home Machines')

    user_housekeeping = User.objects.create_user(username='cleanhome', email='cleanhome@example.com', password='password123', is_company=True)
    company_housekeeping = Company.objects.create(user=user_housekeeping, field='House Keeping')

    user_interiordesign = User.objects.create_user(username='designpro', email='designpro@example.com', password='password123', is_company=True)
    company_interiordesign = Company.objects.create(user=user_interiordesign, field='Interior Design')

    user_locks = User.objects.create_user(username='locksmith', email='locksmith@example.com', password='password123', is_company=True)
    company_locks = Company.objects.create(user=user_locks, field='Locks')

    user_waterheaters = User.objects.create_user(username='hotwater', email='hotwater@example.com', password='password123', is_company=True)
    company_waterheaters = Company.objects.create(user=user_waterheaters, field='Water Heaters')

    user_allinone = User.objects.create_user(username='allinone', email='allinone@example.com', password='password123', is_company=True)
    company_allinone = Company.objects.create(user=user_allinone, field='All in One')

    # Create Services
    # Plumbing Services
    service_plumbing1 = Service.objects.create(company=company_plumber, name='Fix Leaky Faucet', description='Repairing leaky faucets.', price_hour=45.00, field='Plumbing')
    service_plumbing2 = Service.objects.create(company=company_plumber, name='Toilet Repair', description='Repairing clogged or broken toilets.', price_hour=60.00, field='Plumbing')

    # Electricity Services
    service_electrician1 = Service.objects.create(company=company_electrician, name='Light Fixture Installation', description='Installing new light fixtures.', price_hour=55.00, field='Electricity')
    service_electrician2 = Service.objects.create(company=company_electrician, name='Outlet Repair', description='Repairing faulty electrical outlets.', price_hour=50.00, field='Electricity')

    # Carpentry Services
    service_carpenter1 = Service.objects.create(company=company_carpenter, name='Custom Shelving', description='Building custom shelves.', price_hour=70.00, field='Carpentry')
    service_carpenter2 = Service.objects.create(company=company_carpenter, name='Door Repair', description='Repairing or replacing doors.', price_hour=65.00, field='Carpentry')

    # Gardening Services
    service_gardener1 = Service.objects.create(company=company_gardener, name='Lawn Mowing', description='Professional lawn mowing service.', price_hour=30.00, field='Gardening')
    service_gardener2 = Service.objects.create(company=company_gardener, name='Hedge Trimming', description='Trimming and shaping hedges.', price_hour=40.00, field='Gardening')

    # Painting Services
    service_painter1 = Service.objects.create(company=company_painter, name='Interior Painting', description='Painting interior walls.', price_hour=50.00, field='Painting')
    service_painter2 = Service.objects.create(company=company_painter, name='Exterior Painting', description='Painting exterior surfaces.', price_hour=70.00, field='Painting')

    # Air Conditioner Services
    service_ac1 = Service.objects.create(company=company_ac, name='AC Installation', description='Installation of new AC units.', price_hour=120.00, field='Air Conditioner')
    service_ac2 = Service.objects.create(company=company_ac, name='AC Repair', description='Repair and maintenance of AC systems.', price_hour=90.00, field='Air Conditioner')

    # Home Machines Services
    service_homemachines1 = Service.objects.create(company=company_homemachines, name='Washing Machine Repair', description='Repair of washing machines.', price_hour=70.00, field='Home Machines')
    service_homemachines2 = Service.objects.create(company=company_homemachines, name='Dishwasher Installation', description='Installation of dishwashers.', price_hour=60.00, field='Home Machines')

    # House Keeping Services
    service_housekeeping1 = Service.objects.create(company=company_housekeeping, name='Deep Cleaning', description='Thorough deep cleaning of homes.', price_hour=40.00, field='House Keeping')
    service_housekeeping2 = Service.objects.create(company=company_housekeeping, name='Regular Cleaning', description='Regular scheduled home cleaning.', price_hour=30.00, field='House Keeping')

    # Interior Design Services
    service_interiordesign1 = Service.objects.create(company=company_interiordesign, name='Room Consultation', description='Consultation for room design.', price_hour=100.00, field='Interior Design')
    service_interiordesign2 = Service.objects.create(company=company_interiordesign, name='Full Home Design', description='Complete interior design for homes.', price_hour=500.00, field='Interior Design')

    # Locks Services
    service_locks1 = Service.objects.create(company=company_locks, name='Lock Installation', description='Installation of new locks.', price_hour=50.00, field='Locks')
    service_locks2 = Service.objects.create(company=company_locks, name='Emergency Lockout', description='24/7 emergency lockout service.', price_hour=80.00, field='Locks')

    # Water Heaters Services
    service_waterheaters1 = Service.objects.create(company=company_waterheaters, name='Water Heater Repair', description='Repair of water heaters.', price_hour=90.00, field='Water Heaters')
    service_waterheaters2 = Service.objects.create(company=company_waterheaters, name='Water Heater Installation', description='Installation of new water heaters.', price_hour=150.00, field='Water Heaters')

    # All in One Company Services (can create any type)
    service_allinone1 = Service.objects.create(company=company_allinone, name='Emergency Plumbing', description='24/7 emergency plumbing service.', price_hour=80.00, field='Plumbing')
    service_allinone2 = Service.objects.create(company=company_allinone, name='Electrical Inspection', description='Thorough electrical system inspection.', price_hour=75.00, field='Electricity')
    service_allinone3 = Service.objects.create(company=company_allinone, name='Furniture Assembly', description='Assembling flat-pack furniture.', price_hour=40.00, field='Carpentry')

    # Create Service Requests
    ServiceRequest.objects.create(customer=customer1, service=service_plumbing1, address='123 Main St', service_time=2.0)
    ServiceRequest.objects.create(customer=customer2, service=service_electrician1, address='456 Oak Ave', service_time=1.5)
    ServiceRequest.objects.create(customer=customer1, service=service_plumbing1, address='789 Pine Ln', service_time=3.0)
    ServiceRequest.objects.create(customer=customer1, service=service_allinone1, address='101 Elm Rd', service_time=1.0)
    ServiceRequest.objects.create(customer=customer2, service=service_painter1, address='202 Birch Blvd', service_time=4.0)
    ServiceRequest.objects.create(customer=customer1, service=service_ac1, address='303 Cedar Dr', service_time=2.5)
    ServiceRequest.objects.create(customer=customer2, service=service_homemachines1, address='404 Maple Rd', service_time=1.0)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data),
    ]
