services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - netfix_data:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

volumes:
  netfix_data:
